### ISSUE TITLE
Functions Do Not Match with Documentation

### ISSUE THREAD

**Issue by Joseph-Hui** [jivanpal/drat#50] opened 2023-08-10 02:11 UTC
Thank you for your tool. 

My APFS disk failed when I tried to make a backup for it and Google led me here.

I tried the [Drat 0.1.3](https://github.com/jivanpal/drat/releases/tag/v0.1.3) release on a Ubuntu 22 PC and it looks quite different with what the document described. For example, the argument `--container` is not supported in the binary I downloaded. However, in the source code, the argument `--container` appears in `print_usage()`!

Another thing is, when I tried to `recover` a directory or a file, I could not specified where the files to be saved. 

Should I use the pre-built binary or compile one myself?

**Comment by jivanpal** [comment] 2024-01-07 23:14
Hi, apologies for the very delayed response. This is a duplicate of #22, please see there for guidance.

**Closed by jivanpal** 2024-01-07 23:14 UTC
